### ISSUE TITLE
[1.19] Crash when opening keg

### ISSUE THREAD

**Issue by hron84** [hadrus/Alcocraft#2]
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 6/21/22, 6:35 PM
Description: Rendering screen

java.lang.NoSuchMethodError: 'net.minecraftforge.fluids.FluidAttributes net.minecraft.world.level.material.Fluid.getAttributes()'
	at net.hadrus.alcocraft.gui.KegScreen.m_7286_(KegScreen.java:86) ~[alcocraft-1.0.0.jar%2370!/:1.0.0] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:92) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.hadrus.alcocraft.gui.KegScreen.m_6305_(KegScreen.java:178) ~[alcocraft-1.0.0.jar%2370!/:1.0.0] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:382) ~[forge-1.19-41.0.38-universal.jar%23117!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:375) ~[forge-1.19-41.0.38-universal.jar%23117!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1070) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.hadrus.alcocraft.gui.KegScreen.m_7286_(KegScreen.java:86) ~[alcocraft-1.0.0.jar%2370!/:1.0.0] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:92) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.hadrus.alcocraft.gui.KegScreen.m_6305_(KegScreen.java:178) ~[alcocraft-1.0.0.jar%2370!/:1.0.0] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:382) ~[forge-1.19-41.0.38-universal.jar%23117!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:375) ~[forge-1.19-41.0.38-universal.jar%23117!/:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.hadrus.alcocraft.gui.KegScreen
	Mouse location: Scaled: (480, 262). Absolute: (960.000000, 525.000000)
	Screen size: Scaled: (960, 526). Absolute: (1920, 1051). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1070) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['hron84'/210, l='ClientLevel', x=355.56, y=88.00, z=1439.17]]
	Chunk stats: 961, 614
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,75,-32), Section: (at 0,11,0 in 8,4,-2; chunk contains blocks 128,-64,-32 to 143,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 127411 game time, 184925 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:448) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2168) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:677) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23112!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, ExcaliburJEI1.0.zip, Excalibur_Mod_Support_V1.18.1.1.zip, Excalibur_V1.18.1.zip

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.15.48-1-lts
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1452770440 bytes (1385 MiB) / 4831838208 bytes (4608 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: TU116 [GeForce GTX 1660 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16127.09
	Virtual memory used (MB): 11399.67
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 166.50
	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms2048M -Xmx8192M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 470.129.06, NVIDIA Corporation
	Window size: 1920x1051
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/ExcaliburJEI1.0.zip (incompatible), file/Excalibur_Mod_Support_V1.18.1.1.zip (incompatible), file/Excalibur_V1.18.1.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['hron84'/210, l='ServerLevel[Jensens Dimension]', x=355.56, y=88.00, z=1439.17]]
	Data Packs: vanilla, mod:inventorysorter (incompatible), mod:morevillagers, mod:theoneprobe (incompatible), mod:mousetweaks, mod:ftbessentials (incompatible), mod:jei (incompatible), mod:tipsmod (incompatible), mod:sophisticatedcore (incompatible), mod:curios (incompatible), mod:corail_woodcutter, mod:journeymap (incompatible), mod:controlling (incompatible), mod:ftbultimine (incompatible), mod:tombstone, mod:farmingforblockheads (incompatible), mod:bookshelf (incompatible), mod:sophisticatedbackpacks (incompatible), mod:architectury (incompatible), mod:ftblibrary (incompatible), mod:balm (incompatible), mod:carryon (incompatible), mod:ftbteams (incompatible), mod:ftbchunks (incompatible), mod:forge, mod:appleskin, mod:extremesoundmuffler (incompatible), mod:cosmeticarmorreworked (incompatible), mod:craftingtweaks (incompatible), mod:underground_villages, mod:libraryferret, mod:croptopia (incompatible), mod:collective, mod:configured (incompatible), mod:bettervillage, mod:alcocraft, mod:guardvillagers (incompatible), mod:zombievillagersfromspawner, mod:fastleafdecay, mod:replantingcrops, mod:domum_ornamentum, mod:blockui, mod:structurize, mod:buildersaddition (incompatible)
	World Generation: Experimental
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		inventorysorter-1.19-20.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |20.0.0              |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.1.jar                |More Villagers                |morevillagers                 |4.0.1               |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.19-6.0.2.jar                        |The One Probe                 |theoneprobe                   |1.19-6.0.2          |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.22.jar                 |Mouse Tweaks                  |mousetweaks                   |2.22                |DONE      |Manifest: NOSIGNATURE
		ftb-essentials-1900.1.8-build.44.jar              |FTB Essentials                |ftbessentials                 |1900.1.8-build.44   |DONE      |Manifest: NOSIGNATURE
		UndergroundVillages-1.19-1.1.0.jar                |Underground Villages Mod      |underground_villages          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.19-forge-11.0.0.206.jar                     |Just Enough Items             |jei                           |11.0.0.206          |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.53-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.53-ALPHA   |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.19-1.0.3.jar                |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Tips-Forge-1.19-6.0.1.jar                         |Tips                          |tipsmod                       |6.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedcore-1.19-0.3.4.46.jar               |Sophisticated Core            |sophisticatedcore             |1.19-0.3.4.46       |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19-5.1.0.1.jar                     |Curios API                    |curios                        |1.19-5.1.0.1        |DONE      |Manifest: NOSIGNATURE
		corail_woodcutter-1.19-2.4.0.jar                  |Corail Woodcutter             |corail_woodcutter             |2.4.0               |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.52-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.52-ALPHA   |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19-FORGE-2.0.5.jar                    |Croptopia                     |croptopia                     |2.0.5               |DONE      |Manifest: NOSIGNATURE
		collective-1.19.0-4.28.jar                        |Collective                    |collective                    |4.28                |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5rc2-forge.jar                |Journeymap                    |journeymap                    |5.8.5rc2            |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.19-10.0+1.jar                 |Controlling                   |controlling                   |10.0+1              |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.19.jar                         |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		BetterVillage-Forge-1.19-1.0.1.jar                |Better Village                |bettervillage                 |1                   |DONE      |Manifest: NOSIGNATURE
		alcocraft-1.0.0.jar                               |Alcocraft: Beer & Stuff       |alcocraft                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		ftb-ultimine-forge-1900.3.4-build.58.jar          |FTB Ultimine                  |ftbultimine                   |1900.3.4-build.58   |DONE      |Manifest: NOSIGNATURE
		tombstone-8.0.1-1.19.jar                          |Corail Tombstone              |tombstone                     |8.0.1               |DONE      |Manifest: NOSIGNATURE
		structurize-1.19-1.0.417-ALPHA.jar                |Structurize                   |structurize                   |1.19-1.0.417-ALPHA  |DONE      |Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.19-11.0.0.jar        |Farming for Blockheads        |farmingforblockheads          |11.0.0              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19-14.0.5.jar                   |Bookshelf                     |bookshelf                     |14.0.5              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		buildersaddition-1.19-20220612a.jar               |Builders Crafts & Addition    |buildersaddition              |1.19-20220612a      |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19-3.17.5.604.jar        |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19-3.17.5.604     |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.19-1.5.0.jar                     |Guard Villagers               |guardvillagers                |1.4.2               |DONE      |Manifest: NOSIGNATURE
		architectury-5.7.27-forge.jar                     |Architectury                  |architectury                  |5.7.27              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1900.3.7-build.131.jar          |FTB Library                   |ftblibrary                    |1900.3.7-build.131  |DONE      |Manifest: NOSIGNATURE
		zombievillagersfromspawner_1.19.0-1.7.jar         |Zombie Villagers From Spawner |zombievillagersfromspawner    |1.7                 |DONE      |Manifest: NOSIGNATURE
		balm-4.2.0.jar                                    |Balm                          |balm                          |4.2.0               |DONE      |Manifest: NOSIGNATURE
		carryon-1.19-1.18.0.1.jar                         |Carry On                      |carryon                       |1.18.0.1            |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1900.2.7-build.56.jar             |FTB Teams                     |ftbteams                      |1900.2.7-build.56   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1900.3.7-build.154.jar           |FTB Chunks                    |ftbchunks                     |1900.3.7-build.154  |DONE      |Manifest: NOSIGNATURE
		forge-1.19-41.0.38-universal.jar                  |Forge                         |forge                         |41.0.38             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.19        |DONE      |Manifest: NOSIGNATURE
		extremesoundmuffler-3.27_forge-1.19.jar           |Extreme Sound Muffler         |extremesoundmuffler           |3.27_forge-1.19     |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-29.jar                              |FastLeafDecay                 |fastleafdecay                 |29                  |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19-v1b.jar                |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19-v1b            |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		replantingcrops_1.19.0-2.6.jar                    |Replanting Crops              |replantingcrops               |2.6                 |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.19-15.0.0.jar              |CraftingTweaks                |craftingtweaks                |15.0.0              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2c9e9aff-8786-41f0-96a8-db5b8f59fd09
	FML: 41.0
	Forge: net.minecraftforge:41.0.38
```

**Comment by hadrus** [comment]
Fixed
