### ISSUE TITLE
[1.19] The Mod Crashes on launch with forge 41.0.73 or higher

### ISSUE THREAD

**Issue by Saereth** [hadrus/Alcocraft#6]
```
[10:52:03] [modloading-worker-0/INFO]: MinecraftForge v41.0.98 Initialized
[10:52:03] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: alcocraft, class net.hadrus.alcocraft.AlcoCraft
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.98.jar%23249!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23248!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchFieldError: BLOCK_ENTITIES
	at net.hadrus.alcocraft.blocks.AlcoBlockEntities.<clinit>(AlcoBlockEntities.java:12) ~[alcocraft-1.0.1.jar%23144!/:1.0.1]
	at net.hadrus.alcocraft.AlcoCraft.<init>(AlcoCraft.java:35) ~[alcocraft-1.0.1.jar%23144!/:1.0.1]
	... 14 more
```

Pack: FTB One
If you require and further information I'll be glad to provide. Thanks

**Comment by jwrichards1982** [comment]
![Screenshot_20220719_181301](https://user-images.githubusercontent.com/18748296/179874408-e8b36b64-97ec-4ba3-bb0c-60c52df4cfab.png)
Alcocraft, Minecraft 1.19 (stable/latest release downloaded as of 19-July-2022), Forge 41.0.100.
New config, no other mods, still crashes.
[crash-2022-07-19_18.01.07-fml.txt](https://github.com/hadrus/Alcocraft/files/9145644/crash-2022-07-19_18.01.07-fml.txt)
[debug.log](https://github.com/hadrus/Alcocraft/files/9145650/debug.log)
[latest.log](https://github.com/hadrus/Alcocraft/files/9145651/latest.log)
Rollback to 41.0.71 and it still crashes
Different error
![Screenshot_20220719_181521](https://user-images.githubusercontent.com/18748296/179874725-7ea954c6-708c-40fd-a9da-32d5feebe7c1.png)
[crash-2022-07-19_18.15.06-fml.txt](https://github.com/hadrus/Alcocraft/files/9145666/crash-2022-07-19_18.15.06-fml.txt)
[debug.log](https://github.com/hadrus/Alcocraft/files/9145667/debug.log)
[latest.log](https://github.com/hadrus/Alcocraft/files/9145668/latest.log)
Final edit. For now.
Loads with Forge 41.0.45. I went and looked at the date the mod is listed as uploaded on Curseforge. 22-June-2022. The closest Forge release is 41.0.45 on 21-06-2022. I installed that and, without any other mods, a fresh 1.19 download and Alcocraft loaded this time. Hopefully that helps.

One more edit before sleep. 
I have a problem; if something doesn't work, I keep at it until I am utterly annoyed or exhausted.
I did originally have a bunch of mods that seemed to be working fine, adding this broke things. So, in investigating, rolling back mods, upgrading Forge at times when a mod demanded it, I have so far found that 41.0.63 is also a good version. Alcocraft is working as far as I can tell, no more crashes or weird issues like immediate crash when placing a block. Long term, I don't know as I am now needing to get to sleep for my job tomorrow.

**Comment by AmyRose1288** [comment]
there is a API-breaking change at 41.0.60+ & 41.0.90+
and there is a bunch of mods needs manual fixing
